name: cortextool-sync
author: jtlisi
description: "Sync/Diff Prometheus Rules files to with a Cortex cluster."
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  summary:
    description: A summary of changes that will be made if the provided rules are synced.
  detailed:
    description: A detailed description of changes that will be made if the provided rules are synced.
branding:
  icon: "upload"  
  color: "blue"